version: '3.8'

services:
  web-bitcoin-escrow:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/escrow.db}
      - BLOCKCHAIN_API_KEY=${BLOCKCHAIN_API_KEY}
      - ADMIN_SECRET=${ADMIN_SECRET:-your-secret-key-here}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - escrow-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=escrow
      - POSTGRES_USER=escrow_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - escrow-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - escrow-network

volumes:
  postgres_data:
  redis_data:

networks:
  escrow-network:
    driver: bridge
